### ISSUE TITLE
\C is deprecated in regex

### ISSUE THREAD

**Issue by eserte** [kazeburo/WWW-Form-UrlEncoded#1]
See subject. More information on this topic can be found here:  https://metacpan.org/pod/release/RJBS/perl-5.22.0/pod/perldelta.pod#New-Warnings

A sample report where this warning already appears: http://www.cpantesters.org/cpan/report/8ab39dce-0965-11e5-bf14-9f35e0bfc7aa

**Comment by kazeburo** [comment]
Fixed and released v0.22. Thank you!
