### ISSUE TITLE
Build install fails when perl is built with -Ddefault_inc_excludes_dot

### ISSUE THREAD

**Issue by andk** [kazeburo/WWW-Form-UrlEncoded#5]
As per subject. Make install failes with this diagnostics:

``` text
Can't locate builder/MyBuilder.pm in @INC (you may need to install the builder::MyBuilder module) (@INC contains: /tmp/loop_over_bdir-4337-tUL5Im/WWW-Form-UrlEncoded-0.23-0/_build/lib /tmp/loop_over_bdir-4337-tUL5Im/WWW-Form-UrlEncoded-0.23-0/blib/arch /tmp/loop_over_bdir-4337-tUL5Im/WWW-Form-UrlEncoded-0.23-0/blib/lib /home/sand/src/perl/repoperls/installed-perls/host/k93x64xenial/v5.25.10/b4eb/lib/site_perl/5.25.10/x86_64-linux-thread-multi-ld /home/sand/src/perl/repoperls/installed-perls/host/k93x64xenial/v5.25.10/b4eb/lib/site_perl/5.25.10 /home/sand/src/perl/repoperls/installed-perls/host/k93x64xenial/v5.25.10/b4eb/lib/5.25.10/x86_64-linux-thread-multi-ld /home/sand/src/perl/repoperls/installed-perls/host/k93x64xenial/v5.25.10/b4eb/lib/5.25.10) at /tmp/loop_over_bdir-4337-tUL5Im/WWW-Form-UrlEncoded-0.23-0/_build/lib/MyBuilder.pm line 2.
BEGIN failed--compilation aborted at /tmp/loop_over_bdir-4337-tUL5Im/WWW-Form-UrlEncoded-0.23-0/_build/lib/MyBuilder.pm line 2.
Compilation failed in require at ./Build line 40.
BEGIN failed--compilation aborted at ./Build line 40.
```

This leaves the end user back with an unpleasant situation: make test was passing, all seemed well, but the module does not get installed which maybe is discovered only later.

This reminds me of a similar bug report against Mouse: https://github.com/gfx/p5-Mouse/issues/69

Maybe you could also just use a new Minilla and build a new release and it solves this problem?

**Comment by andk** [comment]
BTW, thanks to Darin McBride who brought the case to my attention. He found this report suspect and he was right: http://www.cpantesters.org/cpan/report/4c441020-f8f4-11e6-9a1d-d573a4e77ac8

**Comment by andk** [comment]
I just discovered that there is already a pull request by Todd that also suggests the newer Minilla: https://github.com/kazeburo/WWW-Form-UrlEncoded/pull/4

**Comment by kazeburo** [comment]
Just released 0.24 that was packaged by Minilla 3.x
Thank you!

**Comment by eserte** [comment]
This does not seem to be resolved. With a normally built perl 5.25.11 I see the following installation failure with CPAN.pm:
```
Running Build install
Can't locate builder/MyBuilder.pm in @INC (you may need to install the builder::MyBuilder module) (@INC contains: /home/cpansand/.cpan/build/2017041515/WWW-Form-UrlEncoded-0.24-1/_build/lib /home/cpansand/.cpan/build/2017041515/WWW-Form-UrlEncoded-0.24-1/blib/arch /home/cpansand/.cpan/build/2017041515/WWW-Form-UrlEncoded-0.24-1/blib/lib /opt/perl-5.25.11/lib/site_perl/5.25.11/x86_64-linux /opt/perl-5.25.11/lib/site_perl/5.25.11 /opt/perl-5.25.11/lib/5.25.11/x86_64-linux /opt/perl-5.25.11/lib/5.25.11) at /home/cpansand/.cpan/build/2017041515/WWW-Form-UrlEncoded-0.24-1/_build/lib/MyBuilder.pm line 2.
BEGIN failed--compilation aborted at /home/cpansand/.cpan/build/2017041515/WWW-Form-UrlEncoded-0.24-1/_build/lib/MyBuilder.pm line 2.
Compilation failed in require at ./Build line 40.
BEGIN failed--compilation aborted at ./Build line 40.
```

**Comment by andk** [comment]
Confirmed, that's why I had to release CPAN-2.18-TRIAL. Actually, either Module::Build or CPAN had to be fixed and it seems that the fix in CPAN was more trivial than the equivalent on Module::Build. At the moment I'm waiting that bleadperl integrates CPAN-2.18 and this would fix WWW-Form-UrlEncoded and other Module::Build using modules.

**Comment by eserte** [comment]
Unfortunately there are still situations where installation fails with CPAN-2.18-TRIAL, see https://rt.cpan.org/Ticket/Display.html?id=121665
